services:
  postgres: 
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=catalog-services
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d catalog-services"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: